version: '3'

services: 
  backend-casaterra: 
    build: .
    command: npm run dev
    ports: 
      - '3000:3000'
    volumes: 
      - .:/usr/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    ports: 
      - '3308:3306'
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret